spring:
  application:
    name: apiGatewayService

  cloud:
    gateway:
      routes:
        - id: orderService
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/orders/**
        - id: inventoryService
          uri: lb://INVENTORYSERVICE
          predicates:
            - Path=/inventory/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
