spring:
  application:
    name: apiGatewayService

  cloud:
    gateway:
      routes:
        - id: orderService
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AddRequestHeader=X-Request-Id, Rohan
            - StripPrefix=2
        - id: inventoryService
          uri: lb://INVENTORYSERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - AddRequestHeader=X-Request-Id, Rohan
            - StripPrefix=2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
