jwt:
  secretKey: J/2eCtv4pW7qlF6HQIuKvxU8EuhymVJZzefLq0PAXaY=

server:
  port: 8081
spring:
  application:
    name: apiGatewayService

  cloud:
    gateway:
      routes:
        - id: orderService
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AddRequestHeader=X-Request-Id, Rohan
            - StripPrefix=2
            - name: LoggingOrdersFilter
            - name: Authentication
        - id: inventoryService
          uri: lb://INVENTORYSERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - AddRequestHeader=X-Request-Id, Rohan
            - StripPrefix=2
            - name: Authentication
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
